name: Flight
main: me.ryanclancy000.flight.Flight
version: 1.2
commands:
  flight:
    description: Flight command.
    aliases: fly
    usage: /flight [command] [arg]
permissions:
  flight.admin:
    description: Allows use of all Flight commands.
    children:
      flight.help: true
      flight.toggle: true
      flight.toggle.other: true
      flight.on: true
      flight.on.other: true
      flight.off: true
      flight.off.other: true
      flight.check: true
      flight.check.other: true
      flight.list: true
  flight.help:
    description: Allows use of the help command.
    default: op
  flight.toggle:
    description: Allows use of the toggle command.
    default: op
  flight.toggle.other:
    description: Allows use of the toggle command on other players.
    default: op
  flight.on:
    description: Allows use of the on command.
    default: op
  flight.on.other:
    description: Allows use of the on command on other players..
    default: op
  flight.off:
    description: Allows use of the oh command.
    default: op
  flight.off.other:
    description: Allows use of the off command on other players.
    default: op
  flight.check:
    description: Allows use of the check command.
    default: op
  flight.check.other:
    description: Allows use of the check command on other players.
    default: op
  flight.list:
    description: Allows use of the list command.
    default: op