name: Flight
main: me.ryanclancy000.flight.Flight
version: 0.1
commands:
  flight:
    description: Flight command.
    aliases: fly
    usage: /flight [command] [arg]
permissions:
  flight.self:
    description: Allows use of the fly command.
    default: op