name: Flight
main: me.ryanclancy000.flight.Flight
version: 0.1
commands:
  flight:
    description: Flight command.
    aliases: fly
    usage: /flight [command] [arg]
permissions:
  flight.help:
    description: Allows use of the help command.
    default: op
  flight.toggle:
    description: Allows use of the toggle command.
    default: op
  flight.on:
    description: Allows use of the on command.
    default: op
  flight.off:
    description: Allows use of the oh command.
    default: op
  flight.check:
    description: Allows use of the check command.
    default: op
  flight.list:
    description: Allows use of the list command.
    default: op